//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLINK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public string customer_id { get; set; }
        public string name { get; set; }
        public Nullable<int> service { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public string location { get; set; }
        public string total_price { get; set; }
        public Nullable<int> status { get; set; }
        public string contact { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string worker_id { get; set; }
    
        public virtual Services Services { get; set; }
    }
}
